<?php

namespace App\Http\Livewire\PoTracking;

use Livewire\Component;
use Livewire\WithFileUploads;
use Auth;
use File;

class Importesar extends Component
{
    protected $listeners = [
        'modal-esar'=>'dataesar',
    ];

    use WithFileUploads;
    
    public $file;
    public $app_esar, $appesar, $selected_id, $approvedesar, $file_count, $data_po;
    public function render()
    {
        return view('livewire.po-tracking.importesar');
    }

    public function dataesar($id)
    {
        $this->selected_id = $id;
        $this->data = \App\Models\PoTrackingReimbursementMaster::where('id', $this->selected_id)->first();
        // $this->data_po = \App\Models\PoTrackingReimbursement::select('po_no')->where('id_po_tracking_master', $this->selected_id)->groupBy('po_no')->get();
        $this->approvedesar = $this->data->approved_esar_date_upload;

        // $file = File::files(storage_path('app/public/po_tracking/autogeneratedesar/'.$this->selected_id));

        // $filecount = 0;
        
        // if ($file !== false) {
        //     $filecount = count($file);
        // }
        
        // $filecount;
        // $this->file_count = $filecount;
    }

    public function save()
    {
        $this->validate([
            'file'=>'required|mimes:pdf|max:51200' // 50MB maksimal
        ]);


        if($this->file){
            // $esar = 'autogenerated_esar'.$this->selected_id.'.'.$this->file->extension();
            // $this->file->storePubliclyAs('public/po_tracking/esar/',$esar);

            // $data = \App\Models\PoTrackingReimbursementMaster::where('id', $this->selected_id)->first();


            $esar = 'Approved-Esar-'.$this->selected_id.'.'.$this->file->extension();
            $folderPath = storage_path('app/public/po_tracking/ApprovedEsar/'.$this->selected_id);
            if(!file_exists($folderPath)){
                $response = mkdir($folderPath);
            }
            $this->file->storePubliclyAs('public/po_tracking/ApprovedEsar/'.$this->selected_id.'/',$esar);

            $data = \App\Models\PoTrackingReimbursementMaster::where('id', $this->selected_id)->first();


            $data->approved_esar_date_upload = date('Y-m-d H:i:s');
            $data->save();
        }

        session()->flash('message-success',"Upload Approved ESAR success");

        return redirect()->route('po-tracking.index');
    }
}
