<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreatePoTrackingReimbursementEsarupload extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('po_tracking_reimbursement_esarupload', function (Blueprint $table) {
            $table->id();
            $table->integer('id_po_tracking_master')->nullable();
            $table->char('po_no', 15)->nullable();
            $table->string('autogenerated_esar_filename')->nullable();
            $table->string('approved_esar_filename')->nullable();
            $table->integer('approved_esar_uploader_userid')->nullable();
            $table->datetime('approved_esar_date')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('po_tracking_reimbursement_esarupload');
    }
}
